version: "3.7"

x-odoo-build: &odoo-build
  context: ./17.0
  dockerfile: Dockerfile

services:
      
  db:
    env_file: .env
    image: postgres:14
    container_name: db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5444:5432"
    networks:
      - net1
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo

  odoo1:
    container_name: odoo_replica1
    env_file: .env
    build: *odoo-build
    image: erpgap/odoo17
    restart: "no"
    command: ["/startup.sh"]
    volumes:
      - odoo_home:/var/lib/odoo
      - odoo_extra:/mnt/extra-addons
      - ./17.0/odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db
    networks:
      - net1

volumes:
  db_home:
    external: false
  odoo_home:
    external: false
  odoo_extra:
    external: False
  web_root:
    external: false
  redis_data:
    external: false

networks:
  net1: 
    name: net1
